### ISSUE TITLE
set_edges not properly setting graph_dict

### ISSUE THREAD

**Issue by hunterls97** [jperdomo23/openmht#9]
in graph.py the set edges function doesn't update the graph_dict. I think this is why it takes so long to compute the MWIS since set_edges is used in the global_hypothesis function.

https://github.com/jonperdomo/openmht/blob/641435993fd8e8676b5917b8dd439ef842752fef/openmht/mht.py#L37

Thus, when we get the complement, the current edges will not be removed as there is nothing in the graph_dict when self.__edges is called.

https://github.com/jonperdomo/openmht/blob/641435993fd8e8676b5917b8dd439ef842752fef/openmht/graph.py#L104

This means the degeneracy ordering will be large and there will be a lot of recursive calls.

To fix this, I think the following lines:

https://github.com/jonperdomo/openmht/blob/641435993fd8e8676b5917b8dd439ef842752fef/openmht/graph.py#L84-L85

Just need to be corrected to this

```python
def set_edges(self, edges):
	for edge in edges:
		self.add_edge(edge)
```

Does this make sense or have I overlooked something?

**Comment by jonperdomo** [comment]
Hi, thank you for looking into this. The edges in the `self.__graph_dict` dictionary are not being used to compute MWIS so that doesn't seem to be the case. I only use the edges in the `self.__edges` list for this, so the `set_edges()` function is fine for MWIS. This is confusing so I will remove that redundancy. Here are the top-level function calls:

https://github.com/jonperdomo/openmht/blob/641435993fd8e8676b5917b8dd439ef842752fef/openmht/mht.py#L27-L42

**Comment by hunterls97** [comment]
Ah, I see my mistake now. Thanks
